config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#index'
  resources :micro_bit
  resources :lessons do
    resources :comments, only: [:create]
    resources :likes
  end
  resources :users
  resources :quizzes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    has_one_attached :image
    belongs_to :lesson
    belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    
    has_one_attached :image
    belongs_to :user
    has_many :comments
    has_many :likes, dependent: :destroy
    def like_user(user_id)
        likes.find_by(user_id: user_id)
    end
    
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :lesson, counter_cache: :likes_count
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :lessons
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
      before_action :configure_permitted_parameters, if: :devise_controller?
      
    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
    
    def after_sign_in_path_for(resource)
        lessons_path
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        comment = Comment.create(comment_params)
        redirect_to "/lessons/#{comment.lesson.id}"
        
    end
    
    private
    def comment_params
        params.require(:comment).permit(:text, :image).merge(user_id: current_user.id, lesson_id: params[:lesson_id])
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
    # before_action :move_to_index, except[:index, :show]

    def index
        @lessons = Lesson.includes(:user).order("id DESC").page(params[:page]).per(5)
    end
    
    def new
        @lesson = Lesson.new
    end
    
    def create
        @lesson = Lesson.create(subject: lesson_params[:subject], text: lesson_params[:text], image: lesson_params[:image], user_id: current_user.id)
    end
    
    def destroy
        lesson = Lesson.find(params[:id])
        lesson.destroy if lesson.user_id == current_user.id
    end
    
    def edit
        @lesson = Lesson.find(params[:id])
    end
    
    def update
        lesson = Lesson.find(params[:id])
        if lesson.user_id == current_user.id
            lesson.update(lesson_params)
        end
    end
    
    def show
        @lesson = Lesson.find(params[:id])
        @comment = Comment.new
        @comments = @lesson.comments.includes(:user)
    end
    
    private
        def lesson_params
            params.require(:lesson).permit(:subject, :text, :image)
        end
    
        def move_to_index
            redirect_to action: :index unless user_signed_in?
        end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    
    def create
        @like = Like.create(user_id: current_user.id, lesson_id: params[:lesson_id])
        @like = Like.where(lesson_id: params[:lesson_id])
        @lessons = Lesson.all
    end
    
    def destroy
        like = Like.find_by(user_id: current_user.id, lesson_id: params[:lesson_id])
        like.destroy
        @likes = Like.where(lesson_id: params[:lesson_id])
        @lessons = Lesson.all
    end
    
end

app/controllers/micro_bit_controller.rb
class MicroBitController < ApplicationController
    
    def index
    end
    
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
    def index
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

def index
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @nickname = current_user.nickname
        @lessons = current_user.lessons.order("id DESC").page(params[:page]).per(5)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lesson_helper.rb
module LessonHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/micro_bit_helper.rb
module MicroBitHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lessons/_lessons.html.erb
<div class="content_post">
    <p class="nickname"><%= lesson.user.nickname %>先生の実践</p>
    <p class="subject"><span id="abc"><%= lesson.subject %></span></p>
    <div class="lesson">
        <div class="lesson_text_text"><span id="lesson_text"><%= lesson.text %></span></div>
        <div class="lesson_image"><%= image_tag lesson.image.variant(resize:'280x280'), class:lesson if lesson.image.attached? %></div>
    </div>
    
     <ul class="more_list">
        <li>
            <div class="container2">
                <%= link_to '詳細', "/lessons/#{lesson.id}", class: "btn-denim", method: :get %>
            </div>
        </li>
        <% if user_signed_in? && current_user.id == lesson.user_id %>
        <li>
            <div class="container2">
                 <%= link_to '編集', "/lessons/#{lesson.id}/edit", class: "btn-denim", method: :get %>
            </div>
        </li>
        <li>
            <div class="container2">
                 <%= link_to '削除', "/lessons/#{lesson.id}", class: "btn-denim", method: :delete %>
            </div>
        </li>
        <% end %>    
     </ul> 
</div>

app/views/lessons/create.html.erb
<div class="contents">
    <div class="success">
        <h3>
            投稿が完了しました。ありがとうございます！
        </h3>
        <a class="btn" href="/lessons">授業一覧へ戻る</a>
    </div>
</div>

app/views/lessons/destroy.html.erb
<div class="contents">
    <div class="destroy">
        <h3>
            削除しました。また投稿してくださいね。
        </h3>
        <a class="btn" href="/lessons">授業一覧へ戻る</a>
    </div>
</div>

app/views/lessons/edit.html.erb
<div class="contents">
    <div class=new_box1>
        <%= form_for [@lesson] do |f| %>
           <div style="margin: 8px 0">
                <%= f.label :教科, style: { 'margin-right' => 8 } %>
                <%= f.text_field :subject %>
            </div>
        
            <div style="margin: 8px 0">
                <%= f.label :実践内容, style: { 'margin-right' => 8 } %>
                <%= f.text_area :text, style: 'width: 90%; height: 300px;' %>
            </div>
            
            <div class="field">
                <%= f.file_field :image %>
            </div>
        
            <div class="row">
                <div class="col10 push1">
                  <%= button_tag type: "submit", class: "btn btn--block" do %>
                  編集する<i class="icon-arrow-right"></i>
                  <% end %>
                </div>
            </div>        
        <% end %>

    </div>
</div>

app/views/lessons/index.html.erb
<div class="contents">   
    <div class="lesson_box1">
        <% if user_signed_in? %>  
          <div class="user_nav grid-6">
            <span>〜<%= current_user.nickname %>さんでログイン中〜
                <div class="container">
                  <%= link_to "マイページ","/users/#{current_user.id}", class:'btn-box' %>
                  <%= link_to "投稿する","/lessons/new", class:'btn-box' %>
                </div>
            </span>
          </div>
        <% else %>
          <div class="grid-6">
            <h2>　投稿するにはログイン、またはユーザー登録をお願いします。</h2>
                <div class="container">
                  <%= link_to "ログイン", new_user_session_path, class: "btn-box" %>
                  <%= link_to "新規登録", new_user_registration_path, class: "btn-box" %>
                </div>
          </div>
        <% end %>
        
        <% @lessons.each do |lesson| %>
          <%= render partial: "lessons", locals: { lesson: lesson } %>
        <% end %>
        <%= paginate(@lessons) %>
    </div>
</div>

app/views/lessons/new.html.erb
 <div class="contents">
    <div class=new_box1>
        <%= form_for [@lesson] do |f| %>        
            <div style="margin: 8px 0">
                <%= f.label :教科, style: { 'margin-right' => 8 } %>
                <%= f.text_field :subject, placeholder: 'subject', value: '' %>
            </div>
        
            <div style="margin: 8px 0">
                <%= f.label :実践内容, style: { 'margin-right' => 8 } %>
                <%= f.text_area :text, placeholder: 'lesson', style: 'width: 90%; height: 300px;' %>
            </div>
            
            <div class="field">
                <%= f.file_field :image %>
            </div>
        
            <div class="row">
                <div class="col10 push1">
                  <%= button_tag type: "submit", class: "btn btn--block" do %>
                  投稿する<i class="icon-arrow-right"></i>
                  <% end %>
                </div>
            </div>        
        <% end %>
    </div>
</div>

app/views/lessons/show.html.erb
<div class="space">
</div>
<div class="content_post">
  <!--<div class="lesson_box1">-->
    <% lesson = @lesson %>
    <p class="nickname"><%= lesson.user.nickname %>先生の実践</p>
    <p class="subject"><span id="abc"><%= lesson.subject %></span></p>
    <div class="lesson">
        <div class="lesson_text_text"><span id="lesson_text"><%= lesson.text %></span></div>
        <div class="lesson_image"><%= image_tag lesson.image.variant(resize:'300x300'), class:lesson if lesson.image.attached? %></div>
    </div>
    
    <% if user_signed_in? && current_user.id == lesson.user_id %>
     <ul class="more_list">
        <li>
             <%= link_to '編集', "/lessons/#{lesson.id}/edit", method: :get %>
        </li>
        <li>
             <%= link_to '削除', "/lessons/#{lesson.id}", method: :delete %>
        </li>
     </ul>
    <% end %>
  <!--<div>-->
</div>

<div class="comments">
    <h4>＜コメント一覧＞</h4>
    <% if @comments %>
        <% @comments.each do |comment| %>
                <p>
                    <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>:</strong>
                    <%= comment.text %>
                </p>
                <%= image_tag comment.image.variant(resize:'300x300'), class:comment if comment.image.attached? %>

        <% end %>
    <% end %>
</div>

<div class="commenter">
    <% if current_user %>
         <%= form_for [@lesson, @comment] do |f| %>        
            <div style="margin: 8px 0">
                <%= f.label :コメント, style: { 'margin-right' => 8 } %>
                <%= f.text_area :text, placeholder: 'comments', style: 'width: 90%; height: 300px;' %>
            </div>
            
            <div class="field">
                <%= f.file_field :image %>
            </div>
        
            <div class="row">
                <div class="col10 push1">
                  <%= button_tag type: "submit", class: "btn btn--block" do %>
                  コメントする<i class="icon-arrow-right"></i>
                  <% end %>
                </div>
            </div>        
        <% end %>
    <% end %>
</div>

app/views/lessons/update.html.erb
<div class="contents">
    <div class="edit">
        <h3>
            編集が完了しました。
        </h3>
        <a class="btn" href="/lessons">授業一覧へ戻る</a>
    </div>
</div>

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if lesson.like_user(current_user.id) %>
    <%= button_to lesson_like_path(like, lesson_id: lesson.id), method: :delete, id: "like-button", remote: true do %>
      <%= image_tag("icon_pen1-2.gif") %>
      <span>
        <%= lesson.like_count %>
      </span>
    <% end %>
  <% else %>
    <%= button_to lesson_likes_path(lesson), id: "like-button", remote: true do %>
      <%= image_tag("icon_pen1-8.gif") %>
      <span>
        <%= lesson.like_count %>
      </span>
    <% end %>
  <% end %>
<% else %>
  <%= image_tag("icon_pen1-8.gif") %>
    <span>
      <%= lesson.like_count %>
    </span>
<% end %>

app/views/likes/create.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { lessons: @lessons, likes: @likes, like: @like}) %>");

app/views/likes/destroy.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { lessons: @lessons, likes: @likes }) %>");

app/views/micro_bit/index.html.erb
<div class=micro_bit_box1>
    <h1>ここはマイクロビットのページ</h1>
</div>

app/views/quizzes/index.html.erb
<!doctype html>
<html class="no-js" lang="">

<head>
  <meta charset="utf-8">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="">
  <meta property="og:type" content="">
  <meta property="og:url" content="">
  <meta property="og:image" content="">

  <link rel="manifest" href="site.webmanifest">
  <link rel="apple-touch-icon" href="icon.png">
  <!-- Place favicon.ico in the root directory -->

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">


  <meta name="theme-color" content="#fafafa">
</head>

<body>


  <!--<div class="container">-->
    <div class="blank_box">
    </div>

    <div class="jumbotron mt-5">
      <div class="d-flex justify-content-center">
      
        <div id="js-question" class="mt-3 alert alert-primary" role="alert">
          A simple primary alert—check it out!
        </div>
        
      </div>
      
      <div id="js-items" class="d-flex justify-content-center">
        <div class="m-2">
          <button type="button" id="js-btn-1" class="btn btn-primary">Primary</button>
        </div>
        <div class="m-2">
          <button type="button" id="js-btn-2" class="btn btn-primary">Primary</button>
        </div>
        <div class="m-2">
          <button type="button" id="js-btn-3" class="btn btn-primary">Primary</button>
        </div>
        <div class="m-2">
          <button type="button" id="js-btn-4" class="btn btn-primary">Primary</button>
        </div>
      </div>
    </div>
  </div>
  <script src="app.js"></script>
</body>

</html>

app/views/top/index.html.erb
<div class="contents">
  <div class=box1>
    <div class="slick1">
      <div class=b><img class="c" src="assets/2.jpg"></div>
      <div class=b><img class="c" src="assets/1.jpg"></div>
      <div class=b><img class="c" src="assets/3.jpg"></div>
    </div>
    
    <script type="text/javascript">
      $(function(){
          $('.slick1').slick({
            autoplay: true,
            dots: true,
          });
        });
    </script>
  </div>


  <div class="box2">
    <div class="greeting"><h1>小学校プログラミング教育実践サイト　AP-Laboへようこそ！</h1></div>
    <div class="greeting"><h2>↓実践事例を投稿しよう！↓</h2></div>
    <a href="/lessons"><img class="lesson_link" src="assets/computer_girl.png" alt=""></a>
    <div class="greeting2"><h2>↓クイズに挑戦しよう！↓<h2></div>
    <a href="/quizzes"><img class="quiz_link" src="assets/quiz_man.png" alt=""></a>
  </div>

  <div class=box4>
    <div class="tab-menu">
      <ul class="tab_ul">
        <li id="left" class="selected">アンプラグド</li>
        <li id="center">ソフトウェア</li>
        <li id="right">フィジカル</li>
      </ul>

      <div class="tab_contents">
        <div class="left">
          <p>コンピューターを使わないプログラミング授業</p>
          <%= image_tag "unplugged top.JPG", alt: "お花", id: "assets", class: "image", width: "450px" %>
        </div>
        <div class="center">
          <p>コンピューターの画面内で行うプログラミング授業</p>
          <%= image_tag "kanji top.png", alt: "お花", id: "assets", class: "image", width: "450px" %>
        </div>
        <div class="right">
          <p>ロボットなどを操作して行うプログラミング授業</p>
          <%= image_tag "physical.JPG", alt: "お花", id: "assets", class: "image", width: "450px" %>
        </div>
      </div>
    </div>  
  </div>

  <div class=box3>
    <div class="teaching_materials">
    
      <a href="/micro_bit" target="_blank" > <img class="materials" src="assets/microbit-logo-stacked.png" alt="micro_bit"> </a>
      <img class="materials" src="assets/viscuitbanner.jpg">
      <img class="materials" src="assets/logo_robot.png">
      <img class="materials" src="assets/embot rogo.png">
      <img class="materials" src="assets/scratch rogo.jpg">
    </div>
  </div>
</div

app/views/users/show.html.erb
<div class="user_box1">
    <p><%= @nickname %>さんの実践一覧</p>
    <% @lessons.each do |lesson| %>
      <%= render partial: "lessons/lessons", locals: { lesson: lesson } %>
    <% end %>
    <%= paginate(@lessons) %>
</div>